# Site settings
locale: "en-US"
title: "Olivia 瓶子 / Home"
avatar: "/assets/images/avatar.png"
description: &description ""
baseurl: "" # The subpath of your site, e.g., "/blog"
url: "https://jiapivialiu.github.io" 
repository: "jiapivialiu/jiapivialiu.github.io"

# Author settings
author:
  name: "Jiaping(Olivia) Liu"
  email: "jiaping.liu@stat.ubc.ca"
  avatar: "profile.png"
  bio: "Hi there! I'm a PhD candidate in Statistics at UBC since June 13, 2023."
  location: "Vancouver, BC, CA"
  github: "jiapivialiu"
  googlescholar: "https://scholar.google.com/citations?hl=en&view_op=list_works&gmla=AC6lMd8_hVLqHFVVDzOwgFpZPVra0-5Ot_zjoIAh4iSDcRoI743btxVZNkiYvdC_nzGdeGBY0vFq9mh7SvF-IN-ca5S4CIJ5Wu-AQlvp4iY&user=hbZmyugAAAAJ"
  linkedin: "https://www.linkedin.com/in/jiaping9"
  orcid: "https://orcid.org/0009-0002-8584-5645"

# Build settings
remote_theme: yaoyao-liu/minimal-light
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-avatar

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM

# Exclusions
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Collections
collections:
  posts:
    output: true

# Permalinks
permalink: /:year/:month/:day/:title/

timezone: America/Los_Angeles

# Default settings for pages
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
